/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_limwoon_musicwriter_NativeClass */

#ifndef _Included_com_limwoon_musicwriter_NativeClass
#define _Included_com_limwoon_musicwriter_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_limwoon_musicwriter_NativeClass
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limwoon_musicwriter_NativeClass_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_limwoon_musicwriter_NativeClass
 * Method:    createBefferQueueAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limwoon_musicwriter_NativeClass_createBefferQueueAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_limwoon_musicwriter_NativeClass
 * Method:    createAssetAudioPlayer
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_limwoon_musicwriter_NativeClass_createAssetAudioPlayer
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_limwoon_musicwriter_NativeClass
 * Method:    setPlayingAssetAudioPlayer
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_limwoon_musicwriter_NativeClass_setPlayingAssetAudioPlayer
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_limwoon_musicwriter_NativeClass
 * Method:    setStopAssetAudioPlayer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_limwoon_musicwriter_NativeClass_setStopAssetAudioPlayer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_limwoon_musicwriter_NativeClass
 * Method:    setPitch
 * Signature: (Landroid/content/res/AssetManager;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_limwoon_musicwriter_NativeClass_setPitch
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     com_limwoon_musicwriter_NativeClass
 * Method:    getArrayList
 * Signature: (Ljava/util/ArrayList;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_limwoon_musicwriter_NativeClass_getArrayList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_limwoon_musicwriter_NativeClass
 * Method:    releaseAll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_limwoon_musicwriter_NativeClass_releaseAll
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
